# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

stages:
- stage: 'Dev'
  displayName: 'Deploy to the dev environment'
  #dependsOn: Build
  #condition: |
  #  and
  #  (
  #    succeeded(),
  #    eq(variables['Build.SourceBranchName'], variables['releaseBranchName'])
  #  )
  jobs:
  - deployment: Deploy
    environment: Dev
  - job: 
    steps:
      - task: Kubernetes@1
        inputs:
          connectionType: 'Kubernetes Service Connection'
          kubernetesServiceEndpoint: 'Dev-dev-pos-tms-aks-01-default-1636706749465'
          namespace: 'default'
          command: 'get'
          arguments: 'pods'

- stage: 'Test'
  displayName: 'Deploy to the dev environment'
  dependsOn: Dev
  #condition: |
  #  and
  #  (
  #    succeeded(),
  #    eq(variables['Build.SourceBranchName'], variables['releaseBranchName'])
  #  )
  jobs:
  - deployment: Deploy
    environment: Test
  - job: 
    steps:
      - task: Kubernetes@1
        inputs:
          connectionType: 'Kubernetes Service Connection'
          kubernetesServiceEndpoint: 'Dev-dev-pos-tms-aks-01-default-1636706749465'
          namespace: 'default'
          command: 'get'
          arguments: 'pods'
