name: release
on: workflow_dispatch

env:
  #DOCKER_REGISTRY: docker.pkg.github.com
  DOCKER_REGISTRY: ghcr.io
  GITHUB_PACKAGE: another-package

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo ${DOCKER_REGISTRY}
      #- uses: azure/docker-login@v1
      #  # this logs us into GitHub Packages (docker service)
      #  with:
      #    login-server: docker.pkg.github.com
      #    # login-server: ghcr.io
      #    username: ${GITHUB_ACTOR}
      #    password: ${{ secrets.PAT }}
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${GITHUB_ACTOR}
          password: ${{ secrets.PAT }}
      - name: Pull a known image
        run: docker pull debian:buster-slim
      - name: Re-tag that image
        run: docker image tag debian:buster-slim ${DOCKER_REGISTRY}/${{ github.repository }}/${GITHUB_PACKAGE}:123459
      - name: Push that image
        run: docker push ${DOCKER_REGISTRY}/${{ github.repository }}/${GITHUB_PACKAGE}:123459
