name: release
on: workflow_dispatch

env:
  #DOCKER_REGISTRY: docker.pkg.github.com
  DOCKER_REGISTRY: ghcr.io
  GITHUB_PACKAGE: another-package
  GITHUB_TAG: ${{ github.sha }}

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo ${DOCKER_REGISTRY}
          echo ${GITHUB_ACTOR}
      #- name: Echo2
      #  run: echo ${GITHUB_ACTOR}
      #- uses: azure/docker-login@v1
      #  # this logs us into GitHub Packages (docker service)
      #  with:
      #    login-server: docker.pkg.github.com
          # login-server: ghcr.io
      #    username: ${GITHUB_ACTOR}
      #    password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      #- name: Pull a known image
      #  run: docker pull debian:buster-slim
      #- name: Re-tag that image
      #  run: docker image tag debian:buster-slim ${DOCKER_REGISTRY}/${{ github.repository }}/${GITHUB_PACKAGE}:${GITHUB_TAG}
      # - name: Push that image
      #  run: docker push ${DOCKER_REGISTRY}/${{ github.repository }}/${GITHUB_PACKAGE}:123459
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/${{ env.GITHUB_PACKAGE }}:${{ env.GITHUB_TAG }}
      - name: Dispatch release
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.PAT_BEARER }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/helgedahl/test2/dispatches \
            -d '{"event_type":"package_published","client_payload":{"package":"${GITHUB_PACKAGE}","tag":"${GITHUB_TAG}" }}'
      
